
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue Nov 12 10:09:02 CET 2024
//----------------------------------------------------

package syntax;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int UINT64 = 44;
  public static final int UINT32 = 43;
  public static final int FUNCTION = 64;
  public static final int CHAR = 54;
  public static final int OPERATOR_BOR = 12;
  public static final int EQUALS = 22;
  public static final int RVAL_CHAR = 39;
  public static final int INT64 = 48;
  public static final int INT32 = 47;
  public static final int PARENTH_CLOSE = 28;
  public static final int PARENTH_OPEN = 27;
  public static final int OPERATOR_LEQ = 19;
  public static final int BRACKET_CLOSE = 30;
  public static final int FOR = 61;
  public static final int ELSEIF = 58;
  public static final int OPERATOR_SUB = 3;
  public static final int BOOL = 51;
  public static final int LOOP = 62;
  public static final int IF = 57;
  public static final int TYPE_IDENT = 26;
  public static final int OPERATOR_GT = 16;
  public static final int IDENTIFICATOR = 33;
  public static final int DOT = 25;
  public static final int NUMBER_BIN = 37;
  public static final int EOF = 0;
  public static final int CURLY_OPEN = 31;
  public static final int OPERATOR_MULT = 4;
  public static final int TRUE = 52;
  public static final int error = 1;
  public static final int FLOAT64 = 50;
  public static final int FLOAT32 = 49;
  public static final int COMA = 23;
  public static final int OPERATOR_PP = 20;
  public static final int OPERATOR_MM = 21;
  public static final int SEMI_COLON = 24;
  public static final int OPERATOR_XOR = 8;
  public static final int UINT16 = 42;
  public static final int BRACKET_OPEN = 29;
  public static final int NUMBER_NAT = 34;
  public static final int UINT8 = 41;
  public static final int NUMBER_FLOAT = 36;
  public static final int CURSOR = 63;
  public static final int OPERATOR_NOT = 9;
  public static final int OPERATOR_AND = 6;
  public static final int ELSE = 59;
  public static final int INT16 = 46;
  public static final int WHILE = 60;
  public static final int OPERATOR_DIV = 5;
  public static final int OPERATOR_LT = 17;
  public static final int OPERATOR_GEQ = 18;
  public static final int RVAL_CHAR_ARR = 40;
  public static final int UCHAR = 55;
  public static final int OPERATOR_BNOT = 13;
  public static final int OPERATOR_BAND = 11;
  public static final int OPERATOR_OR = 7;
  public static final int OPERATOR_EQUAL = 14;
  public static final int FALSE = 53;
  public static final int STRUCT = 56;
  public static final int INT8 = 45;
  public static final int CURLY_CLOSE = 32;
  public static final int OPERATOR_ADD = 2;
  public static final int NUMBER_INT = 35;
  public static final int OPERATOR_MOD = 10;
  public static final int NUMBER_HEX = 38;
  public static final int OPERATOR_NEQ = 15;
}

