
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Jan 28 18:16:13 CET 2022
//----------------------------------------------------

package syntax;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int OPERATOR_ADD = 1;
  public static final int OPERATOR_SUB = 2;
  public static final int OPERATOR_MULT = 3;
  public static final int OPERATOR_DIV = 4;
  public static final int OPERATOR_AND = 5;
  public static final int OPERATOR_XOR = 6;
  public static final int OPERATOR_OR = 7;
  public static final int OPERATOR_NOT = 8;
  public static final int OPERATOR_MOD = 9;

  public static final int OPERATOR_BAND = 10;
  public static final int OPERATOR_BOR = 11;
  public static final int OPERATOR_BNOT = 12;
  public static final int OPERATOR_EQUAL = 13;
  public static final int OPERATOR_NEQ = 14;
  public static final int OPERATOR_GT = 15;
  public static final int OPERATOR_LT = 16;
  public static final int OPERATOR_GEQ = 17;
  public static final int OPERATOR_LEQ = 18;

  public static final int OPERATOR_PP = 19;
  public static final int OPERATOR_MM = 20;

  public static final int EQUALS = 21;
  public static final int COMA = 22;
  public static final int SEMI_COLON = 23;
  public static final int DOT = 24;
  public static final int TYPE_IDENT = 25;

  public static final int PARENTH_OPEN = 26;
  public static final int PARENTH_CLOSE = 27;
  public static final int BRACKET_OPEN = 28;
  public static final int BRACKET_CLOSE = 29;
  public static final int CURLY_OPEN = 30;
  public static final int CURLY_CLOSE = 31;

  public static final int SEPARATOR = 32;
  public static final int COMMENT = 33;
  public static final int BLOCK_COMMENT = 34;

  public static final int IDENTIFICATOR = 35;
  public static final int NUMBER_NAT = 36;
  public static final int NUMBER_INT = 37;
  public static final int NUMBER_FLOAT = 38;
  public static final int NUMBER_BIN = 39;
  public static final int NUMBER_HEX = 40;
  public static final int RVAL_CHAR = 41;
  public static final int RVAL_CHAR_ARR = 42;

  public static final int UINT8 = 43;
  public static final int UINT16 = 44;
  public static final int UINT32 = 45;
  public static final int UINT64 = 46;

  public static final int INT8 = 47;
  public static final int INT16 = 48;
  public static final int INT32 = 49;
  public static final int INT64 = 50;

  public static final int FLOAT32 = 51;
  public static final int FLOAT64 = 52;

  public static final int BOOL = 53;
  public static final int TRUE = 54;
  public static final int FALSE = 55;

  public static final int CHAR = 56;
  public static final int UCHAR = 57;

  public static final int STRUCT = 58;

  public static final int IF = 59;
  public static final int ELSEIF = 60;
  public static final int ELSE = 61;

  public static final int WHILE = 62;
  public static final int FOR = 63;
  public static final int LOOP = 64;
  public static final int CURSOR = 65;
  public static final int FUNCTION = 66;

  public static final int EOF = 0;
  public static final int ERROR = -1;
}

